package com.mycompany.uas_pbo;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dion Defindra
 */
public class FormPemesananKamar extends javax.swing.JFrame {

    /**
     * Creates new form FormPemesananKamar
     */
     private PemesananHotel PH = new PemesananHotel();
    public FormPemesananKamar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnStandar = new javax.swing.JButton();
        btnVIP = new javax.swing.JButton();
        btnSuite = new javax.swing.JButton();
        btnSuperior = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtLama = new javax.swing.JTextField();
        btnHasil = new javax.swing.JButton();
        cbJenisKamar = new javax.swing.JComboBox<>();
        cbNoKamar1 = new javax.swing.JComboBox<>();
        cbNoKamar2 = new javax.swing.JComboBox<>();
        cbNoKamar3 = new javax.swing.JComboBox<>();
        cbNoKamar4 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHotel = new javax.swing.JTable();
        btnKeluar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        hslNama = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        hslJenisKamar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        hslHarga = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        hslTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtUang = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        hslKembalian = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEMESANAN HOTEL PARAHYANGAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rincian Kamar Hotel ");

        btnStandar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnStandar.setText("Standar Room");
        btnStandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStandarActionPerformed(evt);
            }
        });

        btnVIP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVIP.setText("VIP Room");
        btnVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIPActionPerformed(evt);
            }
        });

        btnSuite.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSuite.setText("Suite Room");
        btnSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuiteActionPerformed(evt);
            }
        });

        btnSuperior.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        btnSuperior.setText("Superior Room");
        btnSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuperiorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStandar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(btnSuite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStandar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nama Pemesan");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Jenis Kamar");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Nomor Kamar");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Lama Menginap");

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtLama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLamaActionPerformed(evt);
            }
        });

        btnHasil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHasil.setText("Hasil");
        btnHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilActionPerformed(evt);
            }
        });

        cbJenisKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "Standar Room", "VIP Room", "Suite Room", "Superior Room" }));
        cbJenisKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisKamarActionPerformed(evt);
            }
        });

        cbNoKamar1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "Kamar 06", "Kamar 07", "Kamar 08", "Kamar 09", "Kamar 15", "Kamar 16", "Kamar 17", "Kamar 18", "Kamar 19" }));
        cbNoKamar1.setAutoscrolls(true);
        cbNoKamar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbNoKamar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNoKamar1ActionPerformed(evt);
            }
        });

        cbNoKamar2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "Kamar 20", "Kamar 21", "Kamar 22", "Kamar 23", "Kamar 25", "Kamar 26", "Kamar 27", "Kamar 30", "Kamar 31", "Kamar 32", "Kamar 33", "Kamar 40", "Kamar 41", "Kamar 42", "Kamar 43", "Kamar 44", "Kamar 45", "Kamar 46", "Kamar 47", "Kamar 48", "Kamar 49", "Kamar 50", "Kamar 51", "Kamar 52", "Kamar 53", "Kamar 201", "Kamar 202", "Kamar 203", "Kamar 204", "Kamar 205", "Kamar 206", "Kamar 207", "Kamar 208", "Kamar 209", "Kamar 210", "Kamar 211", "Kamar 212" }));
        cbNoKamar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNoKamar2ActionPerformed(evt);
            }
        });

        cbNoKamar3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "Kamar 301", "Kamar 302", "Kamar 303", "Kamar 304", "Kamar 305", "Kamar 306", "Kamar 307", "Kamar 308", "Kamar 309", "Kamar 310", "Kamar 311", "Kamar 312", "Kamar 313", "Kamar 314" }));
        cbNoKamar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNoKamar3ActionPerformed(evt);
            }
        });

        cbNoKamar4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "Kamar 401", "Kamar 402", "Kamar 403", "Kamar 404", "Kamar 405", "Kamar 406" }));
        cbNoKamar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNoKamar4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Suite Room");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Superior Room");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Standar Room");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("VIP Room");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLama)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbNoKamar3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbNoKamar4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama)
                            .addComponent(cbJenisKamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbNoKamar1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(cbNoKamar2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbJenisKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNoKamar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNoKamar2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNoKamar3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNoKamar4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(btnHasil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblHotel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Jenis Kamar", "No Kamar", "Lama Menginap"
            }
        ));
        tblHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHotelMouseClicked(evt);
            }
        });
        tblHotel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                tblHotelComponentMoved(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblHotelComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tblHotel);

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Nama Pemesan");

        hslNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hslNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hslNamaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Jenis Kamar");

        hslJenisKamar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hslJenisKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hslJenisKamarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Harga Kamar");

        hslHarga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hslHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hslHargaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Total");

        hslTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hslTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hslTotalActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Pembayaran");

        txtUang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangActionPerformed(evt);
            }
        });

        btnBayar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Kembalian");

        hslKembalian.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hslKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hslKembalianActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnClear.setText("Hapus");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBayar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(67, 67, 67))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hslNama, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(hslJenisKamar)
                                    .addComponent(hslHarga)
                                    .addComponent(hslTotal)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addGap(46, 46, 46)
                                .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(46, 46, 46)
                                .addComponent(hslKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hslNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(hslJenisKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(hslHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(hslTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(hslKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:cbNoKamar1.setEnabled(true);

    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLamaActionPerformed

    private void btnHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilActionPerformed
        // TODO add your handling code here:

        PH.nama = String.valueOf(txtNama.getText());
        PH.jenis = Float.valueOf(cbJenisKamar.getSelectedIndex());
        PH.lama = Integer.valueOf(txtLama.getText());

        JOptionPane.showMessageDialog(null, "Hasil Terdeteksi");

        hslNama.setText("" + PH.nama);

        if (PH.jenis == 1) {
            hslJenisKamar.setText("Standard Room");
            hslHarga.setText("RP. 200.000/Hari");

        } else if (PH.jenis == 2) {
            hslJenisKamar.setText("VIP Room");
            hslHarga.setText("RP. 275.000/Hari");

        } else if (PH.jenis == 3) {
            hslJenisKamar.setText("Suite Room");
            hslHarga.setText("RP. 300.000/Hari");

        } else if (PH.jenis == 4) {
            hslJenisKamar.setText("Superior Room");
            hslHarga.setText("RP. 350.000/Hari");
        }

        if (PH.jenis == 1) {
            PH.bayar = (int) 200.000;
            PH.tarif = PH.lama * PH.bayar;
            hslTotal.setText("RP. "+PH.tarif+".000");

        } else if (PH.jenis == 2) {
            PH.bayar = (int) 275.000;
            PH.tarif = PH.lama * PH.bayar;
            hslTotal.setText("RP.  "+PH.tarif+".000");
        } else if (PH.jenis == 3) {
            PH.bayar = (int) 300.000;
            PH.tarif = PH.lama * PH.bayar ;
            hslTotal.setText("RP. "+PH.tarif+".000");
        } else if (PH.jenis == 4) {
            PH.bayar = (int) 350.000;
            PH.tarif = PH.lama * PH.bayar;
            hslTotal.setText("RP. "+PH.tarif+".000");
        }

    }//GEN-LAST:event_btnHasilActionPerformed

    private void cbJenisKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisKamarActionPerformed
        // TODO add your handling code here:

        PH.jenis = Float.valueOf(cbJenisKamar.getSelectedIndex());

        if (PH.jenis == 1) {
            cbNoKamar1.setEnabled(true);
            cbNoKamar2.setEnabled(false);
            cbNoKamar3.setEnabled(false);
            cbNoKamar4.setEnabled(false);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);

        } else if (PH.jenis == 2) {
            cbNoKamar1.setEnabled(false);
            cbNoKamar2.setEnabled(true);
            cbNoKamar3.setEnabled(false);
            cbNoKamar4.setEnabled(false);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);

        } else if (PH.jenis == 3) {
            cbNoKamar1.setEnabled(false);
            cbNoKamar2.setEnabled(false);
            cbNoKamar3.setEnabled(true);
            cbNoKamar4.setEnabled(false);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);

        } else if (PH.jenis == 4) {
            cbNoKamar1.setEnabled(false);
            cbNoKamar2.setEnabled(false);
            cbNoKamar3.setEnabled(false);
            cbNoKamar4.setEnabled(true);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cbJenisKamarActionPerformed

    private void cbNoKamar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNoKamar1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbNoKamar1ActionPerformed

    private void cbNoKamar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNoKamar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNoKamar2ActionPerformed

    private void cbNoKamar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNoKamar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNoKamar3ActionPerformed

    private void cbNoKamar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNoKamar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNoKamar4ActionPerformed

    private void tblHotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHotelMouseClicked
        // TODO add your handling code here:
        PH.baris = tblHotel.getSelectedRow();

        PH.jenis = Float.valueOf(cbJenisKamar.getSelectedIndex());
        if (PH.jenis == 0) {
            txtNama.setText(PH.model.getValueAt(PH.baris,0).toString());
            cbJenisKamar.setSelectedItem(PH.model.getValueAt(PH.baris,1).toString());
            cbNoKamar1.setSelectedItem(PH.model.getValueAt(PH.baris,2));
            cbNoKamar2.setSelectedItem(PH.model.getValueAt(PH.baris,2));
            cbNoKamar3.setSelectedItem(PH.model.getValueAt(PH.baris,2));
            cbNoKamar4.setSelectedItem(PH.model.getValueAt(PH.baris,2));
            txtLama.setText(PH.model.getValueAt(PH.baris,3).toString());
        }

        if (PH.jenis == 1) {

            txtNama.setText(PH.model.getValueAt(PH.baris,0).toString());
            cbJenisKamar.setSelectedItem(PH.model.getValueAt(PH.baris,1).toString());
            cbNoKamar1.setSelectedItem(PH.model.getValueAt(PH.baris,2).toString());
            cbNoKamar1.addItem(PH.model.getValueAt(PH.baris,2).toString());
            tblHotel.grabFocus();
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            txtLama.setText(PH.model.getValueAt(PH.baris,3).toString());

        } else if (PH.jenis == 2) {
            txtNama.setText(PH.model.getValueAt(PH.baris,0).toString());
            cbJenisKamar.setSelectedItem(PH.model.getValueAt(PH.baris,1).toString());
            cbNoKamar2.setSelectedItem(PH.model.getValueAt(PH.baris,2).toString());
            cbNoKamar2.addItem(PH.model.getValueAt(PH.baris,2).toString());
            tblHotel.grabFocus();
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            txtLama.setText(PH.model.getValueAt(PH.baris,3).toString());

        } else if (PH.jenis == 3) {
            txtNama.setText(PH.model.getValueAt(PH.baris,0).toString());
            cbJenisKamar.setSelectedItem(PH.model.getValueAt(PH.baris,1).toString());
            cbNoKamar3.setSelectedItem(PH.model.getValueAt(PH.baris,2).toString());
            cbNoKamar3.addItem(PH.model.getValueAt(PH.baris,2).toString());
            tblHotel.grabFocus();
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            txtLama.setText(PH.model.getValueAt(PH.baris,3).toString());

        } else if (PH.jenis == 4) {
            txtNama.setText(PH.model.getValueAt(PH.baris,0).toString());
            cbJenisKamar.setSelectedItem(PH.model.getValueAt(PH.baris,1).toString());
            cbNoKamar4.setSelectedItem(PH.model.getValueAt(PH.baris,2).toString());
            cbNoKamar4.addItem(PH.model.getValueAt(PH.baris,2).toString());
            tblHotel.grabFocus();
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            txtLama.setText(PH.model.getValueAt(PH.baris,3).toString());
        }
    }//GEN-LAST:event_tblHotelMouseClicked

    private void tblHotelComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblHotelComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHotelComponentMoved

    private void tblHotelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblHotelComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHotelComponentShown

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int answer=JOptionPane.showConfirmDialog(null,"Yakin Ingin Keluar","Keluar", JOptionPane.OK_OPTION);
        if(answer==JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void hslNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hslNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hslNamaActionPerformed

    private void hslJenisKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hslJenisKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hslJenisKamarActionPerformed

    private void hslHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hslHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hslHargaActionPerformed

    private void hslTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hslTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hslTotalActionPerformed

    private void txtUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUangActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        PH.uang = Integer.valueOf(txtUang.getText());

        if (PH.jenis == 1) {
            PH.kembalian = (int) PH.uang -  PH.tarif;
            hslKembalian.setText("RP.  "+String.valueOf(PH.kembalian)+".000");
            txtUang.setText("RP.  "+String.valueOf(PH.uang)+".000");
        } else if (PH.jenis == 2) {
            PH.kembalian = (int) PH.uang - PH.tarif;
            hslKembalian.setText("RP.  "+String.valueOf(PH.kembalian)+".000");
            txtUang.setText("RP.  "+String.valueOf(PH.uang)+".000");
        } else if (PH.jenis == 3) {
            PH.kembalian = (int)PH.uang - PH.tarif;
            hslKembalian.setText("RP.  "+String.valueOf(PH.kembalian)+".000");
            txtUang.setText("RP.  "+String.valueOf(PH.uang)+".000");
        } else if (PH.jenis == 4) {
            PH.kembalian = (int) PH.uang - PH.tarif;
            hslKembalian.setText("RP.  "+String.valueOf(PH.kembalian)+".000");
            txtUang.setText("RP.  "+String.valueOf(PH.uang)+".000");
        }
        JOptionPane.showMessageDialog(null, "Anda Sudah Membayar! Silahkan Ambil Kembalian Anda!");
    }//GEN-LAST:event_btnBayarActionPerformed

    private void hslKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hslKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hslKembalianActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here: jenis = Float.valueOf(cbJenisKamar.getSelectedIndex());

        PH.jenis = Float.valueOf(cbJenisKamar.getSelectedIndex());

        if (PH.jenis == 1) {
            PH.model.addRow(new Object[]{
                txtNama.getText(),
                cbJenisKamar.getSelectedItem().toString(),
                cbNoKamar1.getSelectedItem(),
                txtLama.getText(),

            });
            PH.index=cbNoKamar1.getSelectedIndex();
            cbNoKamar1.removeItemAt(PH.index);
            tblHotel.setModel(PH.model);

            txtNama.setText("");
            cbJenisKamar.setSelectedIndex(0);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            txtLama.setText("");
            hslNama.setText("");
            hslHarga.setText("");
            hslJenisKamar.setText("");
            hslTotal.setText("");
            txtUang.setText("");
            hslKembalian.setText("");
            

        } else if (PH.jenis == 2) {

            PH.model.addRow(new Object[]{
                txtNama.getText(),
                cbJenisKamar.getSelectedItem().toString(),
                cbNoKamar2.getSelectedItem(),
                txtLama.getText(),

            });

            PH.index=cbNoKamar2.getSelectedIndex();
            cbNoKamar2.removeItemAt(PH.index);
            tblHotel.setModel(PH.model);

            txtNama.setText("");
            cbJenisKamar.setSelectedIndex(0);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            txtLama.setText("");
            hslNama.setText("");
            hslHarga.setText("");
            hslJenisKamar.setText("");
            hslTotal.setText("");
            txtUang.setText("");
            hslKembalian.setText("");
            

        } else if (PH.jenis == 3) {
            PH.model.addRow(new Object[]{
                txtNama.getText(),
                cbJenisKamar.getSelectedItem().toString(),
                cbNoKamar3.getSelectedItem(),
                txtLama.getText(),

            });
            PH.index=cbNoKamar3.getSelectedIndex();
            cbNoKamar3.removeItemAt(PH.index);
            tblHotel.setModel(PH.model);

            txtNama.setText("");
            cbJenisKamar.setSelectedIndex(0);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            txtLama.setText("");
            hslNama.setText("");
            hslHarga.setText("");
            hslJenisKamar.setText("");
            hslTotal.setText("");
            txtUang.setText("");
            hslKembalian.setText("");
            

        } else if (PH.jenis == 4) {
            PH.model.addRow(new Object[]{
                txtNama.getText(),
                cbJenisKamar.getSelectedItem().toString(),
                cbNoKamar4.getSelectedItem(),
                txtLama.getText(),

            });
            PH.index=cbNoKamar4.getSelectedIndex();
            cbNoKamar4.removeItemAt(PH.index);
            tblHotel.setModel(PH.model);

            txtNama.setText("");
            cbJenisKamar.setSelectedIndex(0);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            txtLama.setText("");
            hslNama.setText("");
            hslHarga.setText("");
            hslJenisKamar.setText("");
            hslTotal.setText("");
            txtUang.setText("");
            hslKembalian.setText("");
           

        }
        cbNoKamar1.setEnabled(false);
        cbNoKamar2.setEnabled(false);
        cbNoKamar3.setEnabled(false);
        cbNoKamar4.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Data Tersimpan!");

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed

        PH.baris = tblHotel.getSelectedRow();
        PH.jenis = Float.valueOf(cbJenisKamar.getSelectedIndex());

        if (PH.jenis == 1) {
            PH.kolom[0] = txtNama.getText();
            PH.kolom[1] = cbJenisKamar.getSelectedItem();
            PH.kolom[2] = cbNoKamar1.getSelectedItem();
            PH.kolom[3] = txtLama.getText();

            tblHotel.setValueAt(PH.kolom[0], PH.baris, 0);
            tblHotel.setValueAt(PH.kolom[1], PH.baris, 1);
            tblHotel.setValueAt(PH.kolom[2], PH.baris, 2);
            tblHotel.setValueAt(PH.kolom[3], PH.baris, 3);

            int index=cbNoKamar1.getSelectedIndex();
            cbNoKamar1.removeItemAt(index);
            txtNama.setText("");
            cbJenisKamar.setSelectedIndex(0);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            txtLama.setText("");        // TODO add your handling code here:
        } else if (PH.jenis == 2) {
            PH.kolom[0] = txtNama.getText();
            PH.kolom[1] = cbJenisKamar.getSelectedItem();
            PH.kolom[2] = cbNoKamar2.getSelectedItem();
            PH.kolom[3] = txtLama.getText();

            tblHotel.setValueAt(PH.kolom[0], PH.baris, 0);
            tblHotel.setValueAt(PH.kolom[1], PH.baris, 1);
            tblHotel.setValueAt(PH.kolom[2], PH.baris, 2);
            tblHotel.setValueAt(PH.kolom[3], PH.baris, 3);

            PH.index=cbNoKamar2.getSelectedIndex();
            cbNoKamar2.removeItemAt(PH.index);
            txtNama.setText("");
            cbJenisKamar.setSelectedIndex(0);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            txtLama.setText("");

        } else if (PH.jenis == 3) {
            PH.kolom[0] = txtNama.getText();
            PH.kolom[1] = cbJenisKamar.getSelectedItem();
            PH.kolom[2] = cbNoKamar3.getSelectedItem();
            PH.kolom[3] = txtLama.getText();

            tblHotel.setValueAt(PH.kolom[0], PH.baris, 0);
            tblHotel.setValueAt(PH.kolom[1], PH.baris, 1);
            tblHotel.setValueAt(PH.kolom[2], PH.baris, 2);
            tblHotel.setValueAt(PH.kolom[3], PH.baris, 3);

            PH.index=cbNoKamar3.getSelectedIndex();
            cbNoKamar3.removeItemAt(PH.index);
            txtNama.setText("");
            cbJenisKamar.setSelectedIndex(0);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            txtLama.setText("");
        } else if (PH.jenis == 4) {
            PH.kolom[0] = txtNama.getText();
            PH.kolom[1] = cbJenisKamar.getSelectedItem();
            PH.kolom[2] = cbNoKamar3.getSelectedItem();
            PH.kolom[3] = txtLama.getText();

            tblHotel.setValueAt(PH.kolom[0], PH.baris, 0);
            tblHotel.setValueAt(PH.kolom[1], PH.baris, 1);
            tblHotel.setValueAt(PH.kolom[2], PH.baris, 2);
            tblHotel.setValueAt(PH.kolom[3], PH.baris, 3);

            PH.index=cbNoKamar4.getSelectedIndex();
            cbNoKamar4.removeItemAt(PH.index);
            txtNama.setText("");
            cbJenisKamar.setSelectedIndex(0);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            txtLama.setText("");
        }
        cbNoKamar1.setEnabled(false);
        cbNoKamar2.setEnabled(false);
        cbNoKamar3.setEnabled(false);
        cbNoKamar4.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Data diubah!");
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        int hapus;
        int baris = tblHotel.getSelectedRow();

        hapus = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Menghapus Data?", "Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);

        if(hapus == 0){

            PH.model.removeRow(baris);
            txtNama.setText("");
            cbJenisKamar.setSelectedIndex(0);
            cbNoKamar1.setSelectedIndex(0);
            cbNoKamar2.setSelectedIndex(0);
            cbNoKamar3.setSelectedIndex(0);
            cbNoKamar4.setSelectedIndex(0);
            cbNoKamar1.setEnabled(false);
            cbNoKamar2.setEnabled(false);
            cbNoKamar3.setEnabled(false);
            cbNoKamar4.setEnabled(false);

            JOptionPane.showMessageDialog(null, "Data Berhasil dihapus!!!");
        }        // TODO add your handling code here:

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuperiorActionPerformed
        // TODO add your handling code here:
        FormRincianSuperior FRP = new  FormRincianSuperior ();
        FRP.setVisible(true);
        FRP.pack();
        FRP.setLocationRelativeTo(null);
        FRP.setDefaultCloseOperation( FormRincianSuperior.EXIT_ON_CLOSE);
         dispose();
    }//GEN-LAST:event_btnSuperiorActionPerformed

    private void btnSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuiteActionPerformed
        // TODO add your handling code here:
        FormRincianSuite FRT = new FormRincianSuite ();
        FRT.setVisible(true);
        FRT.pack();
        FRT.setLocationRelativeTo(null);
        FRT.setDefaultCloseOperation(FormRincianSuite.EXIT_ON_CLOSE);
         dispose();
    }//GEN-LAST:event_btnSuiteActionPerformed

    private void btnVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIPActionPerformed
        // TODO add your handling code here:
        FormRincianVIP FRV = new FormRincianVIP ();
        FRV.setVisible(true);
        FRV.pack();
        FRV.setLocationRelativeTo(null);
        FRV.setDefaultCloseOperation(FormRincianVIP.EXIT_ON_CLOSE);
         dispose();

    }//GEN-LAST:event_btnVIPActionPerformed

    private void btnStandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStandarActionPerformed
        // TODO add your handling code here:
        FormRincianStandar FRS = new FormRincianStandar();
        FRS.setVisible(true);
        FRS.pack();
        FRS.setLocationRelativeTo(null);
        FRS.setDefaultCloseOperation(FormRincianStandar.EXIT_ON_CLOSE);
         dispose();

    }//GEN-LAST:event_btnStandarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPemesananKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPemesananKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPemesananKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPemesananKamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPemesananKamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHasil;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnStandar;
    private javax.swing.JButton btnSuite;
    private javax.swing.JButton btnSuperior;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnVIP;
    private javax.swing.JComboBox<String> cbJenisKamar;
    private javax.swing.JComboBox<String> cbNoKamar1;
    private javax.swing.JComboBox<String> cbNoKamar2;
    private javax.swing.JComboBox<String> cbNoKamar3;
    private javax.swing.JComboBox<String> cbNoKamar4;
    private javax.swing.JTextField hslHarga;
    private javax.swing.JTextField hslJenisKamar;
    private javax.swing.JTextField hslKembalian;
    private javax.swing.JTextField hslNama;
    private javax.swing.JTextField hslTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHotel;
    private javax.swing.JTextField txtLama;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtUang;
    // End of variables declaration//GEN-END:variables
}
